version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./void-audit
      # target: development
    depends_on:
      - redis
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - NET1
    volumes:
      - ./void-audit:/app
      - /app/node_modules
      - reports_data:/app/public/reports
  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - NET1
volumes:
  reports_data:
networks:
  NET1:
    driver: bridge